mutation SignupUser(
  $email: String!
  $password: String! # $students: [StudentInput]
) {
  createUser(params: { email: $email, password: $password }) {
    result {
      ...UserInfo
    }
    error
  }
}

mutation UpdateUser($id: ID!, $email: String) {
  updateUser(params: { id: $id, data: { email: $email } }) {
    result {
      ...UserInfo
    }
    error
  }
}
