# mutation SignupUser(
#   $email: String!
#   $password: String!
#   $firstName: String
#   $lastName: String
#   $dateOfBirth: DateTime
#   $zipCode: String
#   $students: [StudentInput]
# ) {
#   signupUser(
#     signupUserInput: {
#       email: $email
#       password: $password
#       firstName: $firstName
#       lastName: $lastName
#       dateOfBirth: $dateOfBirth
#       zipCode: $zipCode
#       students: $students
#     }
#   ) {
#     ...UserInfo
#   }
# }

mutation GetToken($email: String!, $password: String!) {
  getToken(userCredentials: { email: $email, password: $password }) {
    token {
      accessToken
      tokenType
    }
    error
  }
}
