# mutation AddComment($body: String!, $postId: String!) {
#   addComment(commentInput: { body: $body }, postId: $postId) {
#     id
#     body
#     createdAt
#     user {
#       ...UserInfo
#     }
#   }
# }

mutation CreatePost($title: String!, $content: String!) {
  createPost(params: { title: $title, content: $content }) {
    result {
      ...PostData
    }
    error
  }
}
