query GetAllPosts {
  posts {
    title
    content
  }
}

# query GetPostById($postId: String!) {
#   post(postId: $postId) {
#     id
#     title
#     body
#     truncatedBody
#     favoriteCount
#     naturalCreatedAt
#     commentCount
#     allComments {
#       id
#       body
#       naturalCreatedAt
#       user {
#         ...UserInfo
#       }
#       likeCount
#     }
#     grade
#     createdAt
#     author {
#       ...UserInfo
#     }
#   }
# }
