type Post {
	id: ID!
	title: String!
	truncatedBody: String!
	body: String!
	grade: String
	city: String
	state: String
	zipCode: String
	createdAt: Date!
	updatedAt: Date!
	ups: Int!
	downs: Int!
	score: Int!
	author: User!
}
