# Generated by Django 3.2.5 on 2021-07-23 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Required', max_length=225, verbose_name='Post title')),
                ('description', models.CharField(help_text='Required', max_length=50, verbose_name='Post description')),
            ],
        ),
    ]
