# Generated by Django 3.2.5 on 2021-07-28 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Required', max_length=225, verbose_name='Post title')),
                ('body', models.TextField(help_text='Required', max_length=50, verbose_name='Post body')),
                ('truncated_body', models.CharField(help_text='Required', max_length=50, verbose_name='Truncated body text')),
                ('grade', models.CharField(blank=True, help_text='Required, 2 to 3 letter grade', max_length=3, null=True, verbose_name='Grade focus of post')),
                ('city', models.CharField(blank=True, help_text='Required', max_length=50, null=True, verbose_name='City of Post')),
                ('state', models.CharField(blank=True, help_text='Required, 2 letter US state code', max_length=2, null=True, verbose_name='State of Post')),
                ('zip_code', models.TextField(blank=True, help_text='Required', max_length=8, null=True, verbose_name='Zipcode of Post')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ups', models.IntegerField(default=0, verbose_name='Up votes')),
                ('downs', models.IntegerField(default=0, verbose_name='Down votes')),
                ('score', models.IntegerField(default=0, verbose_name='Vote score')),
            ],
        ),
    ]
