# Generated by Django 3.2.5 on 2021-08-02 03:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pinkle.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Required', max_length=225, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Post title')),
                ('body', models.TextField(help_text='Required', max_length=50, verbose_name='Post body')),
                ('truncated_body', models.CharField(help_text='Required', max_length=50, verbose_name='Truncated body text')),
                ('grade', models.CharField(blank=True, help_text='Required, 2 to 3 letter grade', max_length=3, null=True, verbose_name='Grade focus of post')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('up_votes', models.IntegerField(default=0, verbose_name='Up votes')),
                ('down_votes', models.IntegerField(default=0, verbose_name='Down votes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pinkle.post')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', pinkle.models.IntegerRangeField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pinkle.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
